name:                nyantream
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/myuon/nyantream#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - lens
  - text
  - vector
  - time
  - lens-datetime
  - monad-coroutine
  - authenticate-oauth
  - bytestring
  - conduit
  - resourcet
  - twitter-conduit
  - twitter-types-lens
  - mtl

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - TemplateHaskell

executables:
  nyantream:
    source-dirs:      src
    main:             Main.hs
    ghc-options: -threaded

