name:                nyantream
version:             0.2.1.0
#synopsis:
#description:
homepage:            https://github.com/myuon/nyantream#readme
license:             MIT
author:              myuon
maintainer:          ioi.joi.koi.loi@gmail.com
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - lens
  - text
  - vector
  - time
  - lens-datetime
  - bytestring
  - conduit
  - resourcet
  - twitter-conduit
  - twitter-types-lens
  - mtl
  - text-zipper
  - aeson
  - aeson-lens
  - directory
  - hoauth2
  - http-conduit
  - uri-bytestring
  - gogol-gmail

default-extensions:
  - Strict
  - LambdaCase
  - OverloadedStrings
  - TemplateHaskell
  - TypeApplications
  - RecordWildCards

library:
  source-dirs: src
  ghc-options: -O2

executables:
  nyantream:
    source-dirs:
    - src
    - app
    main: Nyantream.hs
    ghc-options: -threaded -main-is Nyantream

